export default {
    ADD_RULE: 'ADD_RULE',
    DELETE_RULES: 'DELETE_RULES',

    ADD_CONDITION_GROUP: 'ADD_CONDITION_GROUP',
    DELETE_CONDITION_GROUPS: 'DELETE_CONDITION_GROUPS',

    ADD_CONDITION: 'ADD_CONDITION',
    DELETE_CONDITIONS: 'DELETE_CONDITIONS',

    ADD_RESULT: 'ADD_RESULT',
    DELETE_RESULTS: 'DELETE_RESULTS',
    
    DELETE_ALL_LOGIC: 'DELETE_ALL_LOGIC',
    LOAD_LOGIC: 'LOAD_LOGIC',
}