export default {
    ADD_RULE: 'ADD_RULE',
    DELETE_RULES: 'DELETE_RULES',

    ADD_CONDITION: 'ADD_CONDITION',
    DELETE_CONDITIONS: 'DELETE_CONDITIONS',

    ADD_RESULT: 'ADD_RESULT',
    DELETE_RESULTS: 'DELETE_RESULTS',
    UPDATE_RESULT_TYPE: 'UPDATE_RESULT_TYPE',
    UPDATE_RESULT_PARAMS: 'UPDATE_RESULT_PARAMS',
    
    DELETE_ALL_LOGIC: 'DELETE_ALL_LOGIC',
    LOAD_LOGIC: 'LOAD_LOGIC',
}