export default {
    TEST_GAME: 'TEST_GAME',
    FINISH_TEST_GAME: 'FINISH_TEST_GAME',
    RENAME_GAME: 'RENAME_GAME',
    DOWNLOAD_GAME: 'DOWNLOAD_GAME',
    SET_CUSTOM_CSS: 'SET_CUSTOM_CSS',
    CONFIGURE_GAME: 'CONFIGURE_GAME',
    FINISH_CONFIGURE_GAME: 'FINISH_CONFIGURE_GAME',
    SET_GOOGLE_ANALYTICS_ID: 'SET_GOOGLE_ANALYTICS_ID',
    SET_CLOUDINARY_NAME: 'SET_CLOUDINARY_NAME',
    SET_CLOUDINARY_PRESET: 'SET_CLOUDINARY_PRESET',
    SET_OTHER_PARAMETERS: 'SET_OTHER_PARAMETERS',
};