export default {
    ADD_LINK: 'ADD_LINK',
    DELETE_LINK: 'DELETE_LINK',
    DELETE_ALL_LINKS: 'DELETE_ALL_LINKS',
    EDIT_LINK_LABEL: 'EDIT_LINK_LABEL',
    EDIT_LINK_TARGET: 'EDIT_LINK_TARGET',
    LOAD_LINKS: 'LOAD_LINKS',
};