export default {
    ADD_SCREEN_CHOICE: 'ADD_SCREEN_CHOICE',
    DELETE_SCREEN_CHOICE: 'DELETE_SCREEN_CHOICE',
    DELETE_ALL_SCREEN_CHOICES: 'DELETE_ALL_SCREEN_CHOICES',
    EDIT_SCREEN_CHOICE_LABEL: 'EDIT_SCREEN_CHOICE_LABEL',
    EDIT_SCREEN_CHOICE_TARGET: 'EDIT_SCREEN_CHOICE_TARGET',
    LOAD_SCREENS_CHOICES: 'LOAD_SCREENS_CHOICES',
};